---
- name: Download Cobbler source
  get_url:
    url: "{{ cobbler_source_url }}"
    dest: "/root/{{ cobbler_source_file }}" 

- name: Extract cobbler source
  unarchive:
    src: "/root/{{ cobbler_source_file }}"
    dest: /root/
    remote_src: True

- name: Make / Install Cobbler
  shell: make && make install
  args:
    chdir: "/root/{{ cobbler_source_dir }}"
    creates: /etc/cobbler/settings  

- name: Link cobbler python code with python libs
  file:
    src:  /usr/local/lib/python2.7/dist-packages/cobbler
    dest: /usr/lib/python2.7/dist-packages/cobbler
    state: link
    force: True

- name: Set Cobbler Django app secret key
  lineinfile: dest=/usr/local/share/cobbler/web/settings.py  regexp='^SECRET_KEY' line="SECRET_KEY = '{{ cobbler_secret_key }}'"

- name: Enable Apache proxy module
  apache2_module:
    state: present
    name: "{{ item }}" 
  with_items:
    - proxy
    - proxy_http

- name: Enable Cobbler Apache2 conf
  command: a2enconf "{{ item }}"
  with_items:
    - cobbler
    - cobbler_web

- name: Copy wsgi app conf
  copy:
    src: files/cobbler.wsgi
    dest: /usr/local/share/cobbler/web/cobbler.wsgi

- name: Generate htdigest password for web interface and api
  command: htdigest /etc/cobbler/users.digest "Cobbler" cobbler

- name: Set dhcp server interface
  lineinfile: dest=/etc/default/isc-dhcp-server regexp='^INTERFACES=' line=INTERFACES="{{ cobbler_dhcp_interface }}"

- name: Dhcp server config template
  template: src=templates/dhcp.j2 dest=/etc/cobbler/dhcp.template

- name: Install systemd unit for cobbler
  command: cp /etc/cobbler/cobblerd.service /etc/systemd/system/

- name: Restart apache2 service
  systemd:
    name: apache2
    state: reloaded

- name: Start Cobbler service
  systemd:
    state: restarted
    daemon_reload: yes
    name: cobblerd

- name: Wait 2 secs
  pause:
    seconds: 2

- name: Pre-create tftpboot directory
  file:
    path: /tftpboot
    state: directory
    mode: 0755

- name: Get Cobbler loaders
  command: cobbler get-loaders

- name: Run Initial Cobbler sync
  command: cobbler sync

- name: Check cobbler distro list
  shell: cobbler distro list | tr -d ' '
  register: cobbler_distro_list

- debug: var=ubuntu_distro_name

- name: Import Ubuntu ISO contents
  command: cobbler import --name="{{ item }}"  --path /root/iso
  when: item  not in cobbler_distro_list.stdout_lines
  #when: cobbler_distro_list.stdout.find(ubuntu_distro_name) == -1
  with_items: "{{ ubuntu_distro_names }}"

- name: Remove ISO contents
  file:
    path: /root/iso
    state: absent

- name: Update TFTPD xinetd start options
  lineinfile:
    path: /etc/xinetd.d/tftp
    regexp: '^.*server_args'
    line: '        server_args             = -s /tftpboot'

- name: Restart xinetd service
  service:
    name: xinetd
    state: restarted

- name: "Replace 127.0.0.1 with primary ip /etc/cobbler/settings"
  replace:
    dest: /etc/cobbler/settings
    regexp: "127.0.0.1"
    replace: "{{ ansible_default_ipv4.address }}" 
