---
- apt: name=bridge-utils state=present
- name: Setup bridge br-host where "{{ lxc_host_default_if }}" connects to this bridge
  template: src=../templates/interfaces.br-host dest=/etc/network/interfaces
  notify:
    - restart_networking

